
Sun, 26 Dec 2010 20:27:00 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4.1-linux/bin/pypy pidigits.pypy-4.pypy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "pidigits.pypy-4.pypy", line 7, in <module>
    import gmpy
ImportError: No module named gmpy
